
lang <- list(
  ## login
  user = 'Usuario',
  password = 'Contraseña',
  role = 'Permisos',
  recover_password = 'Recuperar contraseña',
  login = 'Iniciar sesión',
  logout = 'Cerrar sesión',
  wrong_user_or_password = 'Usuario o contraseña incorrectos',
  old_password = 'Contraseña anterior',
  new_password_1 = 'Contraseña nueva',
  new_password_2 = 'Repetir contraseña nueva',
  button = 'Aplicar',
  passwords_must_match = 'La contraseña nueva debe ser igual en ambos recuadros',
  password_updated_successfully = 'Contraseña actualizada',
  wrong_current_password = 'Contraseña actual incorrecta',
  add = 'Crear',
  update_password = 'Actualizar contraseña',
  update_role = 'Actualizar permisos',
  delete = 'Eliminar',
  add_success = 'Usuario creado',
  update_password_success = 'Contraseña actualizada',
  update_role_success = 'Permisos actualizados',
  delete_success = 'Usuario eliminado',
  unknown_action = 'Acción desconocida',
  add_error = 'Error al crear usuario. Verifique que el usuario no exista y que tenga permisos menores a los de usted',
  update_password_error = 'Error al actualizar contraseña. Verifique que el usuario no exista y que tenga permisos menores a los de usted',
  update_role_error = 'Error al actualizar permisos. Verifique que el usuario exista y que sus nuevos permisos sean válidos e inferiores a los de usted',
  delete_error = 'Error al eliminar usuario. El usuario no existe o usted no tiene permiso para eliminarlo',
  manage_users = 'Administrar usuarios',
  action = 'Acción',
  selected_user = 'Usuarios disponibles',
  ## UI
  app_name = 'Promo Fulfillment',
  promo = 'Calculadora de Promociones',
  login = 'Login',
  logout = 'Logout',
  password_update = 'Actualizar contraseña',
  user_management = 'Administrar usuarios',
  button = 'Aplicar',
  run = 'Correr',
  reset = 'Reset',
  ok = 'Aceptar',
  cancel = 'Cancelar',
  error = 'Error',
  success = 'Éxito',
  warning = 'Advertencia',
  done = 'Listo',
  days = 'Días',
  weeks = 'Semanas',
  months = 'Meses',
  years = 'Años',
  ## Compute Promotions
  compute_promotions_inputs = 'Inputs',
  compute_promotions_inputs_title = 'Controles principales. Para más ayuda haz click en "(?) Instrucciones".',
  compute_promotions_computation_parameters = 'Exhibiciones',
  compute_promotions_computation_parameters_title = 'Parámetros que afectan el cálculo de las exhibiciones.',
  compute_promotions_impact_parameters = 'Impacto',
  compute_promotions_impact_parameters_title = 'Parámetros que afectan el cálculo de impacto.',
  date_format = 'Formato de fechas',
  grafica_ventas = 'Old_nbr - Formato',
  input_grafica_ventas_title = 'Mostrar gráfica informativa de ventas y forecast.',
  agg_grafica_ventas = 'Sumarización',
  agg_grafica_ventas_names = c('avg' = 'Promedio por tienda', 'sum' = 'Total'),
  graph_toggle = 'Gráfica de ventas/forecast',
  items = 'Items',
  browse = 'Archivo...',
  browse_empty = 'Seleccionar un archivo',
  download = 'Descargar',
  download_summary = 'Resumen',
  download_header = 'HEADER',
  download_detail = 'DETAIL',
  download_template = 'Formato',
  show_instructions = 'Instrucciones',
  tab_input = 'Entradas',
  tab_output_histogram = 'Alcance',
  tab_output_summary = 'Resultados',
  tab_output_table = 'Cálculos',
  feature = 'Promoción',
  bin_size = 'Tamaño del rango',
  summary_groups = 'Nivel de detalle',
  running_query = 'Ejecutando consulta...',
  running_computations = 'Realizando cálculos...',
  plotting = 'Cargando gráfica de ventas...',
  item_error = 'Esta combinación no tiene información :(',
  min_feature_qty_toggle = 'Lógica mínimo',
  toggle_none = 'No hacer nada',
  toggle_round_down = 'Conservadora (qty < min ==> qty := 0)',
  toggle_round_up = 'Agresiva (qty < min ==> qty := min)',
  sspres_benchmark_toggle = 'SSPres Comparativo',
  sspres_benchmark_toggle_none = 'No comparar (SSPres = 0)',
  sspres_benchmark_toggle_current = 'Comparar vs SSPres actual',
  sspres_benchmark_toggle_future = 'Comparar vs SSPres futuro (NO IMPLEMENTADO AÚN)',
  ## Validation
  need_items_file = 'Cargar un archivo de items para comenzar.',
  need_auth = 'Iniciar sesión para continuar.',
  need_input_format = 'Descarga el formato de ejemplo para más información.',
  need_run = 'Click en *Correr* para empezar.',
  need_query_result = 'El query falló :(',
  need_final_result = 'Los cálculos fallaron :(',
  need_select_feature = 'Selecciona una promoción para continuar.',
  ## Variables
  dc = 'CEDIS',
  store_nbr = 'Tienda',
  cid = 'Artículo',
  old_nbr = 'Artículo',
  feature_name = 'Promoción',
  ## Usage Stats
  usage_stats = 'Utilización',
  refresh = 'Refrescar',
  split_by_clearance = 'Separar por nivel de permisos',
  unique_users = 'Usuarios únicos',
  unique_sessions = 'Sesiones únicas'
)

lang$need_valid_input <- paste0('El archivo de items no está en el formato correcto.\n', lang$need_input_format)

## Necesario para que siempre se lean bien los encodings. Si no, de repente hay textos que no se interpretan bien...
lang <- map(lang, enc2native)
