require(purrr)

lang <- list(
  ## login
  user = 'Usuario',
  vp = 'Vicepresidencia',
  all = 'Todos',
  password = 'Contraseña',
  role = 'Permisos',
  recover_password = 'Recuperar contraseña',
  login = 'Iniciar sesión',
  logout = 'Cerrar sesión',
  logout_timeout_info = 'Minutos hasta que se cierre la sesión automáticamente.',
  wrong_user_or_password = 'Usuario o contraseña incorrectos',
  old_password = 'Contraseña anterior',
  new_password_1 = 'Contraseña nueva',
  new_password_2 = 'Repetir contraseña nueva',
  button = 'Aplicar',
  passwords_must_match = 'La contraseña nueva debe ser igual en ambos recuadros',
  password_updated_successfully = 'Contraseña actualizada',
  wrong_current_password = 'Contraseña actual incorrecta',
  add = 'Crear',
  update_password = 'Actualizar contraseña',
  update_role = 'Actualizar permisos',
  delete = 'Eliminar',
  add_success = 'Usuario creado',
  update_password_success = 'Contraseña actualizada',
  update_role_success = 'Permisos actualizados',
  delete_success = 'Usuario eliminado',
  unknown_action = 'Acción desconocida',
  add_error = 'Error al crear usuario. Verifique que el usuario no exista y que tenga permisos menores a los de usted',
  update_password_error = 'Error al actualizar contraseña. Verifique que el usuario no exista y que tenga permisos menores a los de usted',
  update_role_error = 'Error al actualizar permisos. Verifique que el usuario exista y que sus nuevos permisos sean válidos e inferiores a los de usted',
  delete_error = 'Error al eliminar usuario. El usuario no existe o usted no tiene permiso para eliminarlo',
  manage_users = 'Administrar usuarios',
  action = 'Acción',
  selected_user = 'Usuarios disponibles',
  ## UI
  app_name = 'Promo Fulfillment',
  promo = 'Calculadora de Promociones',
  login = 'Login',
  logout = 'Logout',
  access_denied = 'Acceso denegado',
  auto_logout_title = 'La sesión se cerró por inactividad',
  password_update = 'Actualizar contraseña',
  user_management = 'Administrar usuarios',
  button = 'Aplicar',
  run = 'Generar exhibiciones',
  reset = 'Reset',
  ok = 'Aceptar',
  cancel = 'Cancelar',
  error = 'Error',
  success = 'Éxito',
  warning = 'Advertencia',
  done = 'Listo',
  days = 'Días',
  weeks = 'Semanas',
  months = 'Meses',
  years = 'Años',
  help_title = 'Ayuda',
  user_level_icon = '¡Hola %s!',
  ## Compute Promotions
  compute_promotions_inputs = 'Inputs',
  compute_promotions_inputs_title = 'Controles principales. Para más ayuda haz click en "(?) Instrucciones".',
  compute_promotions_computation_parameters = 'Exhibiciones',
  compute_promotions_computation_parameters_title = 'Parámetros que afectan el cálculo de las exhibiciones.',
  compute_promotions_impact_parameters = 'Impacto',
  compute_promotions_impact_parameters_title = 'Parámetros que afectan el cálculo de impacto.',
  date_format = 'Formato de fechas',
  grafica_ventas = 'Promoción - Formato - Old_nbr',
  no_info = 'SIN INFORMACIÓN',
  input_grafica_ventas_title = 'Mostrar gráfica informativa de ventas y forecast.',
  agg_grafica_ventas = 'Sumarización',
  agg_grafica_ventas_names = c('avg' = 'Promedio por tienda', 'sum' = 'Total'),
  graph_toggle = 'Gráfica de ventas/forecast',
  items = 'Items',
  browse = 'Archivo...',
  browse_empty = 'Seleccionar un archivo',
  download = 'Descargar',
  download_summary = 'Resumen',
  download_header = 'HEADER',
  download_detail = 'DETAIL',
  download_template = 'Descargar formato',
  show_instructions = 'Mostrar instrucciones',
  tab_input = 'Entradas',
  tab_output_histogram = 'Alcance',
  tab_output_summary = 'Resultados',
  tab_output_table = 'Cálculos',
  feature = 'Promoción',
  dispersion_graph_title = 'Mostrar información sobre la dispersión de inventario',
  dispersion_toggle = 'Dispersión de inventario',
  bin_size = 'Tamaño del rango',
  bin_number = 'Número de barras',
  summary_groups = 'Nivel de detalle',
  running_query = 'Ejecutando consulta...',
  running_computations = 'Realizando cálculos...',
  plotting = 'Cargando gráfica de ventas...',
  item_error = 'Esta combinación no tiene información :(',
  
  min_feature_qty_toggle = 'Lógica mínimo',
  min_feature_qty_toggle_title = '¿Qué hacer con las tiendas que no llegan a min_feature_qty con los días de venta?',
  min_feature_qty_toggle_names = c('No hacer nada', 'Conservadora (qty < min ==> qty := 0)', 'Agresiva (qty < min ==> qty := min)'),
  
  sspres_benchmark_toggle = 'SSPres Comparativo',
  sspres_benchmark_toggle_title = '¿Contra qué SSPres comparar las sugerencias?',
  sspres_benchmark_toggle_names = c(
    'Comparar vs SSPres futuro',
    'Comparar vs SSPres actual',
    'No comparar (SSPres = 0)'
  ),
  
  impact_toggle = 'Acción SSPres',
  impact_toggle_title = '¿Qué hacer con el SSPres cargado?',
  impact_toggle_names = c('Sustituir', 'Sumar'),
  
  ## Validation
  need_items_file = 'Cargar un archivo de items para comenzar.',
  need_auth = 'Iniciar sesión para continuar.',
  need_input_format = 'Descarga el formato de ejemplo para más información.',
  need_run = 'Click en *Correr* para empezar.',
  need_query_result = 'El query falló :(',
  need_final_result = 'Los cálculos fallaron :(',
  need_select_feature = 'Selecciona una promoción para continuar.',
  ## Variables
  dc = 'CEDIS',
  store_nbr = 'Tienda',
  cid = 'Artículo',
  old_nbr = 'Artículo',
  feature_name = 'Promoción',
  ## Usage Stats
  usage_stats = 'Utilización',
  refresh = 'Refrescar logs',
  update_user_info = 'Refrescar info de usuarios',
  kpi = 'KPI',
  message = 'Evento',
  graph_daily_tab = 'Tendencia',
  graph_daily_x = 'Eje temporal (eje x)',
  graph_daily_split = 'Separar (color)',
  graph_top_tab = 'Top',
  graph_top_split = 'Separar (color)',
  graph_top_x = 'Entidad (eje x)',
  graph_top_nbar = 'Top N',
  active_users = 'Usuarios activos',
  p_active_users = 'Usuarios activos (% de VP)',
  unique_sessions = 'Sesiones únicas',
  n_actions = 'Acciones totales',
  title_error = 'Error',
  graph_top_clearance = 'Nivel de permisos',
  graph_time_tab = 'Desempeño',
  graph_time_title = 'Tiempo de ejecución en segundos',
  graph_time_event = 'Evento',
  graph_time_event_names = c('Query', 'Gráfica de ventas'),
  detail_table_tab = 'Detalle'
)

lang$need_valid_input <- paste0('El archivo de items no está en el formato correcto.\n', lang$need_input_format)
lang$email_name <- 'Replenishment Data Science MX'
lang$email <- 'replen_ds_mx@email.wal-mart.com'
lang$email_subject <- 'Solicitud de activación de Promo Fulfillment'
lang$email_body <- 'Hola, %0A%0AMe gustaría activar mi cuenta en la aplicación Promo Fulfillment, mi usuario es:%0A%0A[Escribe aquí tu usuario de Windows.]'
lang$emailto <- paste0('mailto:', lang$email_name, '<', lang$email, '>', '?subject=', lang$email_subject, '&body=', lang$email_body)

## Necesario para que siempre se lean bien los encodings. Si no, de repente hay textos que no se interpretan bien...
lang <- map(lang, enc2native)
