WITH STORES AS (
  SELECT DISTINCT
    TR.STORE_NBR,
    T.STORE_NAME,
		TR.TRAIT_NBR,
		T.OPEN_STATUS,
		T.OPEN_DATE,
		T.STATE,
		CASE WHEN TR.TRAIT_NBR = 297 THEN 'SUPERCENTER'
		  WHEN TR.TRAIT_NBR = 9 THEN 'BODEGA'
		  WHEN TR.TRAIT_NBR = 11 THEN 'SUPERAMA'
		  WHEN TR.TRAIT_NBR = 1312 THEN 'MIBODEGA'
		  WHEN TR.TRAIT_NBR = 969 THEN 'BAE'
		  WHEN TR.TRAIT_NBR = 136 THEN 'MEDIMART'
		  ELSE 'OTRO'
		END AS NEGOCIO
  FROM
  	MX_CF_VM.TRAIT_STORE AS TR
    INNER JOIN MX_CF_VM.STORE_INFO AS T
      ON TR.STORE_NBR = T.STORE_NBR
	WHERE
	  NEGOCIO IN (?NEGOCIOS)
	  AND (?COND_STR)
	  AND TR.TRAIT_NBR IN (11, 297, 1312, 969, 136, 9)
    AND T.OPEN_STATUS NOT IN (0, 3, 7, 6, 8)
),

CIDS AS (
  SELECT
    DEPT_NBR,
    REPL_GROUP_NBR,
    ITEM_NBR
  FROM
    MX_CF_VM.ITEM A
  WHERE
  	(TRIM(DEPT_NBR)||'.'||TRIM(REPL_GROUP_NBR)) IN (
      SELECT DISTINCT
        (TRIM(DEPT_NBR)||'.'||TRIM(REPL_GROUP_NBR))
      FROM
        MX_CF_VM.ITEM
      WHERE
        OLD_NBR IN (?OLD_NBRS)
    )
),

/*ITEMS AS (
	SELECT
		ITEM_NBR
	FROM
		MX_CF_VM.ITEM_DESC
	WHERE
		ACCT_DEPT_NBR IN (?DEPTS)
		AND OLD_NBR IN (?OLD_NBRS)
		AND STATUS_CODE = 'A'
		AND ORDBK_FLAG = 'Y'
		AND CANCEL_WHEN_OUT_FLAG = 'N'
		AND ITM_MBM_CODE IN ('M', 'I')
),*/

ITEMS_INFO AS (
	SELECT
		I.ITEM_NBR,
		I.PRIME_XREF_ITEM_NBR,
		I.OLD_NBR,
		CAST ((I.VENDOR_NBR * 1000) + (I.VENDOR_DEPT_NBR * 10) + (I.VENDOR_SEQ_NBR) AS INTEGER) AS VENDOR9_NBR,
		I.REPL_GROUP_NBR,
		I.MDSE_CATG_NBR,
		I.SHLF_LIFE_DAYS_QTY,
		CASE
			WHEN I.BRAND_ID IN (
				312625,312627,312624,312633,312626,312629,312631,312630, 312634,312635,312628,312632,315263,
				317731,312648,314450,321588,314614,316405,328877,328870,328774,332303,335021,335023,35347
				)
			THEN 'MARCAS ESTRATEGICAS'
			ELSE 'REGULAR'
		END AS MARCAS_ESTRATEGICAS,	
		ID.ACCT_DEPT_NBR,
		ID.VENDOR_NBR,
		ID.VENDOR_NAME,
		ID.UPC,
		ID.PRIMARY_DESC,
		ID.SIZE_DESC,
		ID.COST,
		ID.VNPK_QTY,
		ID.WHPK_QTY,
		ID.STATUS_CODE,
		ID.TYPE_CODE,
		ID.ITM_MBM_CODE,
		ID.ORDBK_FLAG,
		ID.ORDER_BOOK_SEQUENCE_NUMBER AS SUB_TIPO,
		ID.CANCEL_WHEN_OUT_FLAG,
		ID.ITEM_STORE_TYPE,
		ID.FINELINE,
		SUBSTR(ID.FINELINE,1,2) AS CATEGORY_NBR,
		ID.EFFECTIVE_DATE				
	FROM
		MX_CF_VM.ITEM I
		INNER JOIN MX_CF_VM.ITEM_DESC ID
			ON I.ITEM_NBR = ID.ITEM_NBR
		INNER JOIN CIDS
			ON I.ITEM_NBR = CIDS.ITEM_NBR
	WHERE
		ID.STATUS_CODE = 'A'
		AND ID.ORDBK_FLAG = 'Y'
		AND ID.CANCEL_WHEN_OUT_FLAG = 'N'
		AND ID.ITM_MBM_CODE IN ('M', 'I')
),

INV AS (
	SELECT
		CIDS.REPL_GROUP_NBR,
		CIDS.DEPT_NBR,
		STORES.STORE_NBR,
		--INV.CARRY_OPTION,
		--INV.CARRIED_STATUS,
		SUM(CAST(GREATEST(INV.ON_HAND_1_QTY, 0.00) AS DECIMAL (28,2))) AS OHQTY,
		SUM(CAST(GREATEST(INV.IN_TRANSIT_QTY, 0.00) AS DECIMAL (28,2))) AS ITQTY,
		SUM(CAST(GREATEST(INV.IN_WHS_QTY, 0.00) AS DECIMAL (28,2))) AS IWQTY,
		SUM(CAST(GREATEST(INV.ON_ORDER_QTY, 0.00) AS DECIMAL (28,2))) AS OOQTY
	FROM
		MX_CF_VM.INFOREM_MANAGED_SKU INV
		INNER JOIN CIDS
			ON INV.ITEM_NBR = CIDS.ITEM_NBR
		INNER JOIN STORES
			ON INV.STORE_NBR = STORES.STORE_NBR
	WHERE
		INV.CARRY_OPTION IN ('R')
		AND INV.CARRIED_STATUS IN ('R')
	GROUP BY
		1, 2, 3
),

BASE AS (
	SELECT DISTINCT
		COMBS.SOURCE_DC_NBR AS DC_NBR,
		DC.DC_NAME,
		CIDS.ITEM_NBR,
		CIDS.REPL_GROUP_NBR,
		CIDS.DEPT_NBR,
		ST.STORE_NBR,
		ST.STORE_NAME,
		ST.OPEN_STATUS,
		ST.STATE,
		ST.NEGOCIO
	FROM
		MX_CF_REPL_VM.GRS_FULFILLMENT_PARM AS COMBS
		INNER JOIN CIDS
			ON COMBS.ITEM_NBR = CIDS.ITEM_NBR
		INNER JOIN STORES ST
			ON COMBS.STORE_NBR = ST.STORE_NBR
		LEFT JOIN WW_CORE_DIM_VM.DC_DIM AS DC
			ON COMBS.SOURCE_DC_NBR = DC.DC_NBR
	WHERE
		DC.COUNTRY_CODE IN ('MX')
		AND DC.CURRENT_IND IN ('Y')
),

VENDOR_STATUS AS (
	SELECT
		CAST ((VENDOR_NBR * 1000) + (DEPT_NBR * 10) + (VENDOR_SEQ_NBR) AS INTEGER) AS VENDOR9,
		JDA_VNDR_STAT_CD AS GRS_STATUS,
		VENDOR_TYPE_CD
	FROM
		MX_CF_REPL_VM.GRS_VENDOR_AGREEMENT
	GROUP BY 
		1,2,3
),

CURRWK AS (
  SELECT DISTINCT
  	WM_YR_WK
  FROM
  	MX_CF_VM.CALENDAR_DAY
  WHERE
  	GREGORIAN_DATE = CURRENT_DATE
),

PRE_FCST AS (
  SELECT
		CIDS.REPL_GROUP_NBR,
		CIDS.DEPT_NBR,
    FCST.STORE_NBR,
		FCST.WM_YR_WK,
		SUM(GREATEST(FCST.SALES_FCST_EACH_QTY, 0)) AS WK_FCST_QTY
	FROM
		MX_CF_VM.STORE_ITEM_FCST_WK_CONV AS FCST
    INNER JOIN CURRWK
    	ON FCST.FCST_WM_YR_WK = CURRWK.WM_YR_WK
    INNER JOIN CIDS
    	ON FCST.ITEM_NBR = CIDS.ITEM_NBR
    INNER JOIN STORES
    	ON FCST.STORE_NBR = STORES.STORE_NBR
  WHERE      
		FCST.WM_YR_WK >= ('?WK_INICIO')
		AND FCST.WM_YR_WK <= ('?WK_FINAL')
	GROUP BY 1, 2, 3, 4
),

FCST AS (
	SELECT
		REPL_GROUP_NBR,
		DEPT_NBR,
		STORE_NBR,
		(AVG(WK_FCST_QTY) / 7) AS AVG_DLY_FCST
	FROM
		PRE_FCST
	GROUP BY 1, 2, 3
)

SELECT
	--DISPLAY_KEY,
	BASE.ITEM_NBR,
	BASE.STORE_NBR,
	II.VENDOR9_NBR,
	II.VENDOR_NAME,
	--CASE WHEN GRS_STATUS IS NULL THEN 0 ELSE GRS_STATUS END AS STATUS_GRS,
	BASE.REPL_GROUP_NBR,
	BASE.DEPT_NBR,
	BASE.DC_NBR,
	BASE.DC_NAME,
	II.OLD_NBR,
	II.PRIMARY_DESC,
	II.SIZE_DESC,
	II.FINELINE,
	II.COST,
	II.VNPK_QTY,
	II.WHPK_QTY,
	BASE.STORE_NAME,
	BASE.NEGOCIO,
	BASE.STATE,
	BASE.OPEN_STATUS,
	II.STATUS_CODE,
	--INV.CARRY_OPTION,
	--INV.CARRIED_STATUS,
	II.TYPE_CODE,
	II.ITM_MBM_CODE,
	II.CANCEL_WHEN_OUT_FLAG,
	II.ORDBK_FLAG,
	II.SUB_TIPO,
	II.CATEGORY_NBR,
	ZEROIFNULL(INV.OHQTY) AS OH_QTY,
	ZEROIFNULL(FCST.AVG_DLY_FCST) AS AVG_DLY_FCST
FROM
	BASE
	INNER JOIN ITEMS_INFO II
		ON BASE.ITEM_NBR = II.ITEM_NBR
	LEFT JOIN INV
		ON BASE.REPL_GROUP_NBR = INV.REPL_GROUP_NBR AND BASE.DEPT_NBR = INV.DEPT_NBR AND BASE.STORE_NBR = INV.STORE_NBR
	LEFT JOIN FCST
		ON BASE.REPL_GROUP_NBR = FCST.REPL_GROUP_NBR AND BASE.DEPT_NBR = FCST.DEPT_NBR AND BASE.STORE_NBR = FCST.STORE_NBR
WHERE
	(TRIM(BASE.DEPT_NBR)||'.'||TRIM(II.OLD_NBR)||'.'||TRIM(BASE.NEGOCIO)) IN (?KEY)
/*
	INV
	LEFT JOIN ITEMS_INFO II
		ON INV.ITEM_NBR = II.ITEM_NBR
	LEFT JOIN DC
		ON INV.ITEM_NBR = DC.ITEM_NBR AND INV.STORE_NBR = DC.STORE_NBR
	LEFT JOIN FCST
		ON INV.REPL_GROUP_NBR = FCST.REPL_GROUP_NBR AND INV.STORE_NBR = FCST.STORE_NBR
FROM

--=================Tabla General (TG) de combinaciones ITST activas, validas y con inventario de Articulos Resurtibles. Contiene especificaciones del articulo, banderas de validez, inventario en piezas y a costo==============

	(
		SELECT DISTINCT
		TRIM(T3.ACCT_DEPT_NBR)||'.'||TRIM(T3.OLD_NBR)||'.'||TRIM(T5.NEGOCIO) AS DISPLAY_KEY,
		TRIM(T3.ACCT_DEPT_NBR)||'.'||TRIM(SUBSTR(T3.FINELINE,1,2)) AS LLAVEDEPCAT,
		TRIM(T3.UPC)||TRIM(T1.STORE_NBR) AS LLAVEUPC,
		
		/*T3.ACCT_DEPT_NBR,
		T3.VENDOR_NBR,
		CAST ((T2.VENDOR_NBR*1000)+(T2.VENDOR_DEPT_NBR*10)+(T2.VENDOR_SEQ_NBR) AS INTEGER ) AS VENDOR9_NBR,
		T3.VENDOR_NAME,
		T3.UPC,
		T2.REPL_GROUP_NBR AS CID,
		T3.ITEM_NBR,*/
		--DC.SOURCE_DC_NBR AS DC_NBR,
		--DC2.DC_NAME,
		/*T3.OLD_NBR,
		T3.PRIMARY_DESC,
		T3.SIZE_DESC,
		T3.COST,
		T3.VNPK_QTY,
		T3.WHPK_QTY,
		T3.STATUS_CODE,
		T3.TYPE_CODE,
		T3.ITM_MBM_CODE,
		T3.ORDBK_FLAG,
		T3.ORDER_BOOK_SEQUENCE_NUMBER AS SUB_TIPO,
		T3.CANCEL_WHEN_OUT_FLAG,
		T3.ITEM_STORE_TYPE,
		T3.FINELINE,
		SUBSTR(T3.FINELINE,1,2) AS CATEGORY_NBR,
		T2.MDSE_CATG_NBR,
		T3.EFFECTIVE_DATE,	
		T2.SHLF_LIFE_DAYS_QTY,
		CASE WHEN T2.BRAND_ID IN (312625,312627,312624,312633,312626,312629,312631,312630, 312634,312635,312628,312632,315263,317731,312648,314450,321588,314614,316405,328877,328870,328774,332303,335021,335023,35347) THEN 'MARCAS ESTRATEGICAS' ELSE 'REGULAR' END AS MARCAS_ESTRATEGICAS,									
		*/
		/*T1.STORE_NBR,
		T4.STORE_NAME,
		T5.NEGOCIO,
		T4.OPEN_STATUS,
		T4.OPEN_DATE,
		T4.STATE,
		T1.CARRY_OPTION,
		T1.CARRIED_STATUS,
		SUM(CAST (CASE WHEN T1.ON_HAND_1_QTY<0.00 THEN  0.00 ELSE  T1.ON_HAND_1_QTY END AS DECIMAL (28,2))) AS OHQTY,
		SUM(CAST (CASE WHEN T1.ON_HAND_1_QTY<0.00 THEN  0.00 ELSE  T1.ON_HAND_1_QTY*T3.COST END AS DECIMAL (28,2))) AS OHCOST,
		
		SUM(CAST (CASE WHEN T1.IN_TRANSIT_QTY<0.00 THEN  0.00 ELSE  T1.IN_TRANSIT_QTY END AS DECIMAL (28,2))) AS ITQTY,
		SUM(CAST (CASE WHEN T1.IN_TRANSIT_QTY<0.00 THEN  0.00 ELSE  T1.IN_TRANSIT_QTY*T3.COST END AS DECIMAL (28,2))) AS ITCOST,
		
		SUM(CAST (CASE WHEN T1.IN_WHS_QTY<0.00 THEN  0.00 ELSE  T1.IN_WHS_QTY END AS DECIMAL (28,2))) AS IWQTY,
		SUM(CAST (CASE WHEN T1.IN_WHS_QTY<0.00 THEN  0.00 ELSE  T1.IN_WHS_QTY*T3.COST END AS DECIMAL (28,2))) AS IWCOST,
		
		SUM(CAST (CASE WHEN T1.ON_ORDER_QTY<0.00 THEN  0.00 ELSE  T1.ON_ORDER_QTY END AS DECIMAL (28,2))) AS OOQTY,
		SUM(CAST (CASE WHEN T1.ON_ORDER_QTY<0.00 THEN  0.00 ELSE  T1.ON_ORDER_QTY*T3.COST END AS DECIMAL (28,2))) AS OOCOST*/
		
		
		--FROM
		--MX_CF_VM.INFOREM_MANAGED_SKU	T1,
		--MX_CF_VM.ITEM T2,
		--MX_CF_VM.ITEM_DESC T3,
		--MX_CF_VM.STORE_INFO T4,
		--(SELECT DISTINCT STORE_NBR, TRAIT_NBR, CASE WHEN TRAIT_NBR=297 THEN 'SUPERCENTER' WHEN TRAIT_NBR=9 THEN 'BODEGA' WHEN TRAIT_NBR=11 THEN 'SUPERAMA' WHEN TRAIT_NBR=1312 THEN 'MIBODEGA' WHEN TRAIT_NBR=969 THEN 'BAE'WHEN TRAIT_NBR=136 THEN 'MEDIMART' ELSE 'OTRO' END AS NEGOCIO FROM MX_CF_VM.TRAIT_STORE WHERE TRAIT_NBR IN (11,297,1312,969,136,9)) T5,
		--MX_CF_REPL_VM.GRS_FULFILLMENT_PARM AS DC,
		--WW_CORE_DIM_VM.DC_DIM AS DC2
		
		--WHERE
		--T1.ITEM_NBR=T2.ITEM_NBR
		--AND T1.ITEM_NBR=T3.ITEM_NBR
		--AND T4.STORE_NBR = T1.STORE_NBR
		--AND T4.STORE_NBR=T5.STORE_NBR
		--AND T1.ITEM_NBR = DC.ITEM_NBR
		--AND T5.STORE_NBR = DC.STORE_NBR
		--AND DC.SOURCE_DC_NBR = DC2.DC_NBR
		--AND DISPLAY_KEY IN (?KEY)
		--AND T3.OLD_NBR IN (?OLD_NBRS)
		--AND (?COND_STR)
		--AND T3.STATUS_CODE IN ('A')
		--AND T3.ORDBK_FLAG IN ('Y')
		--AND T3.CANCEL_WHEN_OUT_FLAG IN ('N')
		--AND T3.ITM_MBM_CODE IN ('M', 'I')
		--AND CARRY_OPTION IN ('R')
		--AND CARRIED_STATUS IN ('R')
		--AND OPEN_STATUS NOT IN (0,3,7,6,8)
		--AND DC2.COUNTRY_CODE IN ('MX')
		--AND DC2.CURRENT_IND IN ('Y')
		
		--GROUP BY
		--1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
		
	--) AS TG
	
	--LEFT JOIN

--=================Tabla Vendor Status. Contiene Status de los proveedores a 9 digitos (0, 1 o 2)==============

/*	(
	
		SELECT
		CAST ((VENDOR_NBR*1000)+(DEPT_NBR*10)+(VENDOR_SEQ_NBR) AS INTEGER ) AS VENDOR9,
		JDA_VNDR_STAT_CD AS GRS_STATUS,
		VENDOR_TYPE_CD
		
		FROM
		MX_CF_REPL_VM.GRS_VENDOR_AGREEMENT
		
		GROUP BY 
		1,2,3
		
	) AS VENDOR_STATUS*/
		
	--ON (VENDOR_STATUS.VENDOR9=TG.VENDOR9_NBR)
	
	
--	LEFT JOIN

--=================Tabla FCST. Obtiene el promedio de Forecast Diario de los old_nbr y semanas que se incluyan en los filtros==============
	
	/*(

		SELECT

			T2.STORE_NBR,
			I.PRIME_XREF_ITEM_NBR,
			AVG(T2.WK_FCST_QTY) AS AVG_WKLY_FCST
		
		FROM
			(
				-- Pre sumarizar los diveros fcst types
				SELECT STORE_NBR, ITEM_NBR, WM_YR_WK, SUM(SALES_FCST_EACH_QTY) AS WK_FCST_QTY 
				FROM MX_CF_VM.STORE_ITEM_FCST_WK_CONV 
				WHERE FCST_WM_YR_WK = (SELECT DISTINCT WM_YR_WK FROM MX_CF_VM.CALENDAR_DAY WHERE GREGORIAN_DATE = CURRENT_DATE)
				GROUP BY 1,2,3
			) AS T2
				INNER JOIN MX_CF_VM.ITEM AS I
					ON T2.ITEM_NBR = I.ITEM_NBR
		
		WHERE
			T2.WM_YR_WK >= ('?WK_INICIO')
			AND T2.WM_YR_WK <= ('?WK_FINAL')
			AND I.REPL_GROUP_NBR IN (
				SELECT REPL_GROUP_NBR
				FROM MX_CF_VM.ITEM
				WHERE OLD_NBR IN (?OLD_NBRS)
			)

		GROUP BY 1,2
		
	) AS FCST*/
	
	--ON (FCST.PRIME_XREF_ITEM_NBR = TG.ITEM_NBR AND FCST.STORE_NBR = TG.STORE_NBR)

--GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31*/

