WITH STORES AS (
  SELECT DISTINCT
    TR.STORE_NBR,
    T.STORE_NAME,
		T.OPEN_STATUS,
		T.STATE,
		CASE WHEN TR.TRAIT_NBR = 297 THEN 'SUPERCENTER'
		  WHEN TR.TRAIT_NBR = 9 THEN 'BODEGA'
		  WHEN TR.TRAIT_NBR = 11 THEN 'SUPERAMA'
		  WHEN TR.TRAIT_NBR = 1312 THEN 'MIBODEGA'
		  WHEN TR.TRAIT_NBR = 969 THEN 'BAE'
		  WHEN TR.TRAIT_NBR = 136 THEN 'MEDIMART'
		  ELSE 'OTRO'
		END AS NEGOCIO
  FROM
  	MX_CF_VM.TRAIT_STORE AS TR
    INNER JOIN MX_CF_VM.STORE_INFO AS T
      ON TR.STORE_NBR = T.STORE_NBR
	WHERE
	  NEGOCIO IN (?NEGOCIOS)
	  AND (?COND_STR)
	  AND TR.TRAIT_NBR IN (11, 297, 1312, 969, 136, 9)
    AND T.OPEN_STATUS NOT IN (0, 3, 7, 6, 8)
),

CIDS AS (
  SELECT
    DEPT_NBR,
    REPL_GROUP_NBR,
    ITEM_NBR
  FROM
    MX_CF_VM.ITEM A
  WHERE
  	(TRIM(DEPT_NBR)||'.'||TRIM(REPL_GROUP_NBR)) IN (
      SELECT DISTINCT
        (TRIM(DEPT_NBR)||'.'||TRIM(REPL_GROUP_NBR))
      FROM
        MX_CF_VM.ITEM
      WHERE
        OLD_NBR IN (?OLD_NBRS)
    )
),

ITEMS_INFO AS (
	SELECT
		I.ITEM_NBR,
		I.OLD_NBR,
		CAST ((I.VENDOR_NBR * 1000) + (I.VENDOR_DEPT_NBR * 10) + (I.VENDOR_SEQ_NBR) AS INTEGER) AS VENDOR9_NBR,
		I.REPL_GROUP_NBR,
		ID.ACCT_DEPT_NBR,
		ID.VENDOR_NAME,
		ID.PRIMARY_DESC,
		ID.SIZE_DESC,
		ID.COST,
		ID.VNPK_QTY,
		ID.WHPK_QTY,
		ID.STATUS_CODE,
		ID.TYPE_CODE,
		ID.ITM_MBM_CODE,
		ID.ORDBK_FLAG,
		ID.ORDER_BOOK_SEQUENCE_NUMBER AS SUB_TIPO,
		ID.CANCEL_WHEN_OUT_FLAG,
		ID.FINELINE,
		SUBSTR(ID.FINELINE,1,2) AS CATEGORY_NBR
	FROM
		MX_CF_VM.ITEM I
		INNER JOIN MX_CF_VM.ITEM_DESC ID
			ON I.ITEM_NBR = ID.ITEM_NBR
		INNER JOIN CIDS
			ON I.ITEM_NBR = CIDS.ITEM_NBR
	WHERE
		ID.STATUS_CODE = 'A'
		AND ID.ORDBK_FLAG = 'Y'
		AND ID.CANCEL_WHEN_OUT_FLAG = 'N'
		AND ID.ITM_MBM_CODE IN ('M', 'I')
),

INV AS (
	SELECT
		CIDS.REPL_GROUP_NBR,
		CIDS.DEPT_NBR,
		STORES.STORE_NBR,
		INV.CARRY_OPTION,
		INV.CARRIED_STATUS,
		SUM(CAST(GREATEST(INV.ON_HAND_1_QTY, 0.00) AS DECIMAL (28,2))) AS OHQTY
	FROM
		MX_CF_VM.INFOREM_MANAGED_SKU INV
		INNER JOIN CIDS
			ON INV.ITEM_NBR = CIDS.ITEM_NBR
		INNER JOIN STORES
			ON INV.STORE_NBR = STORES.STORE_NBR
	WHERE
		INV.CARRY_OPTION IN ('R')
		AND INV.CARRIED_STATUS IN ('R')
	GROUP BY
		1, 2, 3, 4, 5
),

BASE AS (
	SELECT DISTINCT
		COMBS.SOURCE_DC_NBR AS DC_NBR,
		DC.DC_NAME,
		CIDS.ITEM_NBR,
		CIDS.REPL_GROUP_NBR,
		CIDS.DEPT_NBR,
		ST.STORE_NBR,
		ST.STORE_NAME,
		ST.OPEN_STATUS,
		ST.STATE,
		ST.NEGOCIO
	FROM
		MX_CF_REPL_VM.GRS_FULFILLMENT_PARM AS COMBS
		INNER JOIN CIDS
			ON COMBS.ITEM_NBR = CIDS.ITEM_NBR
		INNER JOIN STORES ST
			ON COMBS.STORE_NBR = ST.STORE_NBR
		LEFT JOIN WW_CORE_DIM_VM.DC_DIM AS DC
			ON COMBS.SOURCE_DC_NBR = DC.DC_NBR
	WHERE
		DC.COUNTRY_CODE IN ('MX')
		AND DC.CURRENT_IND IN ('Y')
),

VENDOR_STATUS AS (
	SELECT
		CAST ((VENDOR_NBR * 1000) + (DEPT_NBR * 10) + (VENDOR_SEQ_NBR) AS INTEGER) AS VENDOR9,
		JDA_VNDR_STAT_CD AS GRS_STATUS
	FROM
		MX_CF_REPL_VM.GRS_VENDOR_AGREEMENT
),

CURRWK AS (
  SELECT DISTINCT
  	WM_YR_WK
  FROM
  	MX_CF_VM.CALENDAR_DAY
  WHERE
  	GREGORIAN_DATE = CURRENT_DATE
),

PRE_FCST AS (
  SELECT
		CIDS.REPL_GROUP_NBR,
		CIDS.DEPT_NBR,
    FCST.STORE_NBR,
		FCST.WM_YR_WK,
		SUM(GREATEST(FCST.SALES_FCST_EACH_QTY, 0)) AS WK_FCST_QTY
	FROM
		MX_CF_VM.STORE_ITEM_FCST_WK_CONV AS FCST
    INNER JOIN CURRWK
    	ON FCST.FCST_WM_YR_WK = CURRWK.WM_YR_WK
    INNER JOIN CIDS
    	ON FCST.ITEM_NBR = CIDS.ITEM_NBR
    INNER JOIN STORES
    	ON FCST.STORE_NBR = STORES.STORE_NBR
  WHERE      
		FCST.WM_YR_WK BETWEEN (?WK_INICIO) AND (?WK_FINAL)
	GROUP BY 1, 2, 3, 4
),

FCST AS (
	SELECT
		REPL_GROUP_NBR,
		DEPT_NBR,
		STORE_NBR,
		(AVG(WK_FCST_QTY) / 7) AS AVG_DLY_FCST
	FROM
		PRE_FCST
	GROUP BY 1, 2, 3
)

SELECT
	(TRIM(BASE.DEPT_NBR)||'.'||TRIM(II.OLD_NBR)||'.'||TRIM(BASE.NEGOCIO)) AS DISPLAY_KEY,
	BASE.ITEM_NBR,
	BASE.STORE_NBR,
	II.VENDOR9_NBR,
	II.VENDOR_NAME,
	ZEROIFNULL(VS.GRS_STATUS) AS STATUS_GRS,
	BASE.REPL_GROUP_NBR AS CID,
	II.ACCT_DEPT_NBR,
	BASE.DC_NBR,
	BASE.DC_NAME,
	II.OLD_NBR,
	II.PRIMARY_DESC,
	II.SIZE_DESC,
	II.FINELINE,
	II.COST,
	II.VNPK_QTY,
	II.WHPK_QTY,
	BASE.STORE_NAME,
	BASE.NEGOCIO,
	BASE.STATE,
	BASE.OPEN_STATUS,
	II.STATUS_CODE,
	INV.CARRY_OPTION,
	INV.CARRIED_STATUS,
	II.TYPE_CODE,
	II.ITM_MBM_CODE,
	II.CANCEL_WHEN_OUT_FLAG,
	II.ORDBK_FLAG,
	II.SUB_TIPO,
	II.CATEGORY_NBR,
	ZEROIFNULL(INV.OHQTY) AS OH_QTY,
	ZEROIFNULL(FCST.AVG_DLY_FCST) AS AVG_DLY_FCST
FROM
	BASE
	INNER JOIN ITEMS_INFO II
		ON BASE.ITEM_NBR = II.ITEM_NBR
	LEFT JOIN VENDOR_STATUS VS
		ON II.VENDOR9_NBR = VS.VENDOR9
	LEFT JOIN INV
		ON BASE.REPL_GROUP_NBR = INV.REPL_GROUP_NBR AND BASE.DEPT_NBR = INV.DEPT_NBR AND BASE.STORE_NBR = INV.STORE_NBR
	LEFT JOIN FCST
		ON BASE.REPL_GROUP_NBR = FCST.REPL_GROUP_NBR AND BASE.DEPT_NBR = FCST.DEPT_NBR AND BASE.STORE_NBR = FCST.STORE_NBR
WHERE
	DISPLAY_KEY IN (?KEY)
