SELECT DISTINCT

TG.OLD_NBR,
NEGOCIO,
FCST.WM_YR_WK,

SUM(FCST.WK_FCST_QTY) AS WKLY_QTY

FROM
	(
		WITH T5 AS
		(SELECT DISTINCT STORE_NBR, TRAIT_NBR, CASE WHEN TRAIT_NBR=297 THEN 'SUPERCENTER' WHEN TRAIT_NBR=9 THEN 'BODEGA' WHEN TRAIT_NBR=11 THEN 'SUPERAMA' WHEN TRAIT_NBR=1312 THEN 'MIBODEGA' WHEN TRAIT_NBR=969 THEN 'BAE'WHEN TRAIT_NBR=136 THEN 'MEDIMART' ELSE 'OTRO' END AS NEGOCIO FROM MX_CF_VM.TRAIT_STORE WHERE TRAIT_NBR IN (11,297,1312,969,136,9))
		
		SELECT DISTINCT
		T1.STORE_NBR,
		T3.OLD_NBR,
		T3.ITEM_NBR,
		T5.NEGOCIO

		FROM
		MX_CF_VM.INFOREM_MANAGED_SKU T1
		INNER JOIN MX_CF_VM.ITEM_DESC AS T3 ON T1.ITEM_NBR = T3.ITEM_NBR
		INNER JOIN MX_CF_VM.STORE_INFO AS T4 ON T4.STORE_NBR = T1.STORE_NBR
		INNER JOIN T5 ON T1.STORE_NBR = T5.STORE_NBR
		
		WHERE
		T3.OLD_NBR IN (?OLD_NBRS)
		AND T5.NEGOCIO LIKE ('?NEGOCIO')
		AND T3.STATUS_CODE IN ('A')
		AND T3.ORDBK_FLAG IN ('Y')
		AND T3.CANCEL_WHEN_OUT_FLAG IN ('N')
		AND T3.ITM_MBM_CODE IN ('M', 'I')
		AND T4.OPEN_STATUS NOT IN (0,3,7,6,8)
		AND T1.CARRY_OPTION IN ('R')
		AND T1.CARRIED_STATUS IN ('R')
	) AS TG
	
	
	LEFT JOIN
	(
		WITH T1 AS  (SELECT PRIME_XREF_ITEM_NBR, ITEM_NBR	FROM MX_CF_VM.ITEM WHERE OLD_NBR IN (?OLD_NBRS))
		
		SELECT
			T2.STORE_NBR,
			T1.PRIME_XREF_ITEM_NBR,
			T2.WM_YR_WK,
			T2.WK_FCST_QTY
		
		FROM
			(
				WITH CURRWK AS (SELECT DISTINCT WM_YR_WK FROM MX_CF_VM.CALENDAR_DAY WHERE GREGORIAN_DATE = CURRENT_DATE)
				SELECT STORE_NBR, ITEM_NBR, A.WM_YR_WK, SUM(SALES_FCST_EACH_QTY) AS WK_FCST_QTY 
				FROM MX_CF_VM.STORE_ITEM_FCST_WK_CONV A
				INNER JOIN CURRWK ON FCST_WM_YR_WK = CURRWK.WM_YR_WK
				GROUP BY 1,2,3
			) AS T2
			INNER JOIN T1 	ON T2.ITEM_NBR = T1.ITEM_NBR

	) AS FCST
	
	ON (FCST.PRIME_XREF_ITEM_NBR = TG.ITEM_NBR AND FCST.STORE_NBR = TG.STORE_NBR)										

GROUP BY 1,2,3
ORDER BY 1,2,3
