SELECT
	RRP.ITEM_NBR AS OLD_NBR,
	RRP.RETAIL_READY_PACK_IND AS RRP_IND,
	CASE
		WHEN UCC.ITEM_SYNC_STAT_CD = 1003 THEN 'Y'
		ELSE 'N'
	END AS GS1_SYNCED
FROM
	MXITEM.ITEM_EXT AS RRP
	LEFT JOIN (
		SELECT
			ITEM_NBR,
			ITEM_SYNC_STAT_CD
		FROM
			MXITEM.ITEM_UCCNET
	) AS UCC
		ON RRP.ITEM_NBR = UCC.ITEM_NBR
--WHERE
	--RRP.ITEM_NBR IN (?OLD_NBRS)
