SELECT
	FORMATO,
	ITEM_NBR,
	OLD_NBR,
	ITEM_DESC,
	WM_YR_WK,
	UPC,
	CID,
	VP,
	DIVISION,
	DEP_NBR,
	CATEGORY_NBR,
	FINELINE,
	CLASIFICACION,
	CATALOGO,
	FALT_OH,
	FALT_OH_IT,
	FALT_OH_IT_IW,
	FALT_TTL,
	1 - (FALT_OH * 1.0000 / CATALOGO * 1.0000) AS IS_OH,
	1 - (FALT_TTL * 1.0000 / CATALOGO * 1.0000) AS IS_TTL	

FROM
	MR101_WM_AD_HOC.IS_ACUM_ITEM_VF

WHERE
	OLD_NBR IN (9506783)
	AND FORMATO IN ('BAE')
	AND WM_YR_WK >= (11930)
	AND WM_YR_WK <= (11934)

ORDER BY
	1, 2, 3, 4, 5
