SELECT
	VP,
	DIVISION,
	DEP_NBR,
	CATEGORY_NBR,
	CID,
	ITEM_NBR,
	OLD_NBR,
	FORMATO,
	WM_YR_WK,
	SUM(CATALOGO) AS CATALOGO,
	SUM(FALT_OH) AS FALT_OH,
	SUM(FALT_OH_IT) AS FALT_OH_IT,
	SUM(FALT_OH_IT_IW) AS FALT_OH_IT_IW,
	SUM(FALT_TTL) AS FALT_TTL,
	1 - (SUM(FALT_OH) * 1.0000 / SUM(CATALOGO) * 1.0000) AS IS_OH,
	1 - (SUM(FALT_TTL) * 1.0000 / SUM(CATALOGO) * 1.0000) AS IS_TTL	

FROM
	MR101_WM_AD_HOC.IS_ACUM_ITEM_VF

WHERE
	OLD_NBR IN (?OLD_NBRS)
	AND FORMATO IN (?NEGOCIOS)
	AND WM_YR_WK >= (?WK_INI_STUD)
	AND WM_YR_WK <= (?WK_FIN_STUD)

GROUP BY
	1, 2, 3, 4, 5, 6, 7, 8, 9
ORDER BY
	1, 2, 3, 4, 5, 6, 7, 8, 9
