SELECT
	RRP.ITEM_NBR,
	RRP.RETAIL_READY_PACK_IND,
	CASE
		WHEN UCC.ITEM_SYNC_STAT_CD = 1003 THEN 'Y'
		ELSE 'N'
	END AS GS1_SYNC_STATUS
FROM
	MXITEM.ITEM_EXT AS RRP
	LEFT JOIN MXITEM.ITEM_UCCNET AS UCC
		ON RRP.ITEM_NBR = UCC.ITEM_NBR
--WHERE
	--RRP.ITEM_NBR IN (?OLD_NBRS)
