WITH
ITEMS AS (
	SELECT
		ITEM_NBR,
		OLD_NBR,
		REPL_GROUP_NBR
	FROM
		MX_CF_VM.ITEM
	WHERE
		OLD_NBR IN (?OLD_NBRS)
),
STORES AS (
  SELECT DISTINCT
		STORE_NBR,
		CASE
			WHEN TRAIT_NBR = 297 THEN 'SUPERCENTER'
			WHEN TRAIT_NBR = 9 THEN 'BODEGA'
			WHEN TRAIT_NBR = 11 THEN 'SUPERAMA'
			WHEN TRAIT_NBR = 1312 THEN 'MIBODEGA'
			WHEN TRAIT_NBR IN (136, 969) THEN 'BAE'
			ELSE 'OTRO'
		END AS NEGOCIO
	FROM
		MX_CF_VM.TRAIT_STORE
	WHERE
		NEGOCIO IN ('?NEGOCIOS')
),
STR_ITEM_QTY AS (
	SELECT
		GRS_PROMOTION_ID,
		ITEM_NBR,
		OLD_NBR,
		SUBSTR(GRS_LOC_ID, 12, 4) AS STORE_NBR,
		OVRD_PRESENTATION_QTY AS SSPRES
	FROM
		MX_CF_REPL_VM.GRS_DMDUNIT_PROMO A
		INNER JOIN ITEMS ON (A.REPL_GROUP_NBR = ITEMS.REPL_GROUP_NBR)
		INNER JOIN STORES ON (SUBSTR(GRS_LOC_ID, 12, 4) = STORES.STORE_NBR)
	WHERE
		OVRD_PRESENTATION_QTY > 0
),
PROMO_DET AS (
	SELECT
		GRS_PROMOTION_ID,
		PROMOTION_ID,
		PROMO_CREATE_DATE,
		PROMO_START_DATE,
		(PROMO_START_DATE + (PROMO_DURATION_NBR / 1440)) AS PROMO_END_DATE,
		PROMO_PRIORITY_NBR,
		ADDITIVE_SWITCH_CNT
	FROM
		MX_CF_REPL_VM.GRS_PROMOTION
	WHERE
		PROMO_STATUS_TYPE_CD IN (7, 9)
		AND PROMOTION_ID NOT LIKE 'DEFAULT'
		AND PROMOTION_ID NOT LIKE 'ARR-PLAN'
		AND PROMOTION_ID NOT LIKE 'Discontinuation PROFILE'
		AND PROMOTION_ID NOT LIKE 'APER%'
		--Starts before end date and ends after start date (all the ones overlaping the study period)
		AND (PROMO_START_DATE <= '?END_DATE' AND PROMO_END_DATE >= '?START_DATE')
)
SELECT
	ITEM_NBR,
	OLD_NBR,
	STORE_NBR,
	SSPRES,
	PROMOTION_ID,
	PROMO_CREATE_DATE,
	PROMO_START_DATE,
	PROMO_END_DATE
	PROMO_PRIORITY_NBR,
	ADDITIVE_SWITCH_CNT
FROM
	STR_ITEM_QTY
	INNER JOIN PROMO_DET ON
		STR_ITEM_QTY.GRS_PROMOTION_ID = PROMO_DET.GRS_PROMOTION_ID
ORDER BY 1, 2, 3, 4, 5
