WITH
SSG AS
(SELECT
T1.ITEM_NBR,
T3. STORE_NBR AS STORE_NBR,
T3.SAFETY_EACH_QTY AS SSGanador
FROM  
MX_CF_VM.ITEM  T1,
MX_CF_REPL_VM.GRS_FCST_DEMAND   T3

WHERE

T1.ITEM_NBR=T3.ITEM_NBR

AND  T3.FCST_DATE = DATE),


SST AS 
(SELECT 
ITEM_NBR,
STORE_NBR,
SUM (SSPress) AS SSPress,
SUM(DISPLAY) AS DISPLAY
 
FROM

(SELECT

SSP.ITEM_NBR,
SSP.STORE_NBR,
SSP.SSPress,
DISPLAY,
ESTRATEGIA

FROM

(SELECT DISTINCT
T1.ITEM_NBR,
T2. DEST_STORE_NBR AS STORE_NBR,
T2.PRESENTATION_QTY AS SSPress,
T2.DISPLAY_QTY AS DISPLAY,
T2.SS_PRESN_SOURCE_NAME AS ESTRATEGIA

FROM  
MX_CF_VM.ITEM  T1,
MX_CF_REPL_VM.GRS_PRESENTATION_PARM  T2
WHERE
T1.ITEM_NBR=T2.ITEM_NBR
AND SS_PRESN_SOURCE_NAME <>'DEFAULT'

AND EFF_DATE<=DATE
AND EXPIRE_DATE>DATE

) SSP

)SSTT

GROUP BY 1,2),


BPR AS
(SELECT 
ITEM_NBR,
DEST_STORE_NBR AS STORE_NBR,
MAX(PRESENTATION_QTY) AS Base_Press

FROM  

MX_CF_REPL_VM.GRS_PRESENTATION_PARM 

WHERE SS_PRESN_SOURCE_NAME ='DEFAULT'
AND EFF_DATE<=DATE
AND (EXPIRE_DATE>DATE OR EXPIRE_DATE='1970-01-01')
GROUP BY 1,2),


MAX_SS AS
(SELECT
 
T1.ITEM_NBR AS ITEM_NBR,
T2.STORE_NBR,
T2.MAX_SS_QTY AS MAXSS,
T2.MIN_SS_QTY AS MINSS,
T2.MIN_SS_SUPPLY_DAY_QTY AS SSCOV

FROM 
                
MX_CF_VM.ITEM                                                T1,
MX_CF_REPL_VM.GRS_FULFILLMENT_PARM  T2

WHERE
T1.ITEM_NBR=T2.ITEM_NBR),


SSC AS
(SELECT 

T1.ITEM_NBR,
T1.STORE_NBR,
ZEROIFNULL(T2.SS_ADJUST_INV_DAY_QTY) AS SSTEMP

FROM

MX_CF_REPL_VM.GRS_FULFILLMENT_PARM T1

LEFT JOIN

(SELECT 
A.SS_EVENT_NAME,
A.MAX_EFF,
B.SS_ADJUST_INV_DAY_QTY

FROM

(SELECT

SS_EVENT_NAME,                  
MAX(SS_EVENT_EFF_DATE) AS MAX_EFF
FROM 
MX_CF_REPL_VM.SAFETY_STOCK_EVENT 

WHERE  SS_EVENT_EFF_DATE<= DATE

GROUP BY 1)A

LEFT JOIN

MX_CF_REPL_VM.SAFETY_STOCK_EVENT  B  ON(A.SS_EVENT_NAME=B.SS_EVENT_NAME AND A.MAX_EFF=B.SS_EVENT_EFF_DATE)) T2

ON (T1.SS_EVENT_NAME=T2.SS_EVENT_NAME))


SELECT 

SSG.ITEM_NBR,
SSG.STORE_NBR,

ZEROIFNULL(CAST(SST.SSPRESS AS DECIMAL(19,2 )))  AS SS_PRESS,
ZEROIFNULL(CAST(SST.DISPLAY AS DECIMAL(19,2 )))  AS DISPLAY,

ZEROIFNULL(CAST(BPR.BASE_PRESS AS DECIMAL(19,2 ))) AS BASE_PRESS,
ZEROIFNULL(CAST(SSG.SSGANADOR AS DECIMAL(19,2 ))) AS SS_GANADOR,
ZEROIFNULL(CAST(MAX_SS.MAXSS  AS DECIMAL(19,2 ))) AS MAX_SS,
ZEROIFNULL(CAST(MAX_SS.MINSS  AS DECIMAL(19,2 )))  AS MIN_SS,

ZEROIFNULL(CAST(MAX_SS.SSCOV  AS DECIMAL(19,2 ))) AS SSCOV_,
ZEROIFNULL(CAST(SSC.SSTEMP  AS DECIMAL(19,2 ))) AS SSTEMP_,
(SSCOV_+SSTEMP_) AS SSCOV_TOT,

(SS_Press+BASE_PRESS) AS SS_PRESS_Tot ,

CASE 
WHEN SS_GANADOR=MAX_SS THEN 'MAX_SS'
WHEN SS_GANADOR=MIN_SS THEN 'MIN_SS'
WHEN SS_GANADOR BETWEEN SS_Press - 0.2 AND SS_Press + 0.2 THEN 'SS_PRESS'
WHEN SS_GANADOR BETWEEN BASE_PRESS - 0.05 AND BASE_PRESS + 0.05 THEN 'BASE_PRESS'
WHEN SS_GANADOR BETWEEN SS_PRESS_Tot - 0.05 AND  SS_PRESS_Tot + 0.05 THEN 'SS_PRESS_Tot'
--WHEN SS_GANADOR BETWEEN SSCOV_PIEZAS - 0.2 AND SSCOV_PIEZAS + 0.2 THEN 'SSCOV'
--WHEN SS_GANADOR BETWEEN SSTEMP_PIEZAS - 0.2 AND SSTEMP_PIEZAS + 0.2 THEN 'SSTEMP'
--WHEN SS_GANADOR BETWEEN SSCOV_TOT_PIEZAS - 0.2 AND SSCOV_TOT_PIEZAS + 0.2 THEN 'SSCOV_Tot'
WHEN SS_GANADOR=SS_PRESS THEN 'SS_PRESS'
WHEN SS_GANADOR=SS_PRESS+BASE_PRESS THEN 'SS_PRESS_Tot'
WHEN SS_GANADOR=SS_Press/2 THEN 'SS_PRESS'
--WHEN SSCOV_PIEZAS BETWEEN SS_GANADOR* 0.9 AND SS_GANADOR*1.1  THEN  'SSCOV'
--WHEN SSTEMP_PIEZAS BETWEEN SS_GANADOR*0.9 AND SS_GANADOR*1.1  THEN  'SSTEMP'
--WHEN SSCOV_TOT_PIEZAS BETWEEN SS_GANADOR*0.9 AND SS_GANADOR*1.1  THEN  'SSCOV_Tot'
ELSE 'OTRO' END AS GANADOR

FROM
SSG
LEFT JOIN SST ON SSG.ITEM_NBR=SST.ITEM_NBR AND SSG.STORE_NBR=SST.STORE_NBR
LEFT JOIN BPR ON SSG.ITEM_NBR=BPR.ITEM_NBR AND SSG.STORE_NBR=BPR.STORE_NBR
LEFT JOIN MAX_SS ON  SSG.ITEM_NBR=MAX_SS.ITEM_NBR  AND  SSG.STORE_NBR=MAX_SS.STORE_NBR
LEFT JOIN SSC ON  SSG.ITEM_NBR=SSC.ITEM_NBR  AND  SSG.STORE_NBR=SSC.STORE_NBR
