
SELECT DISTINCT
	TRIBU,
	"USER",
	"NAME",
	PUESTO
FROM WM_AD_HOC.TABLA_ASIGNACION
	UNPIVOT (
		("USER", "NAME") FOR PUESTO IN (
			(TRIBE_LEAD_ID, TRIBE_LEAD_NAME) AS 'TRIBE_LEAD',
			(SQUAD_LEAD_ID, SQUAD_LEAD_NAME) AS 'SQUAD_LEAD',
			(CATEGORY_MANAGER_ID, CATEGORY_MANAGER_NAME) AS 'CATEGORY_MANAGER_LEAD',
			(CATEGORY_SUPPLY_LEAD_ID, CATEGORY_SUPPLY_LEAD_NAME) AS 'CATEGORY_SUPPLY_LEAD',
			(CATEGORY_SUPPLY_MANAGER_ID, CATEGORY_SUPPLY_MANAGER_NAME) AS 'CATEGORY_SUPPLY_MANAGER',
			(CATEGORY_SUPPLY_ASSOCIATE_ID, CATEGORY_SUPPLY_ASSOCIATE_NAME) AS 'CATEGORY_SUPPLY_ASSOCIATE'
		)
	) AS A
WHERE
	"USER" NOT IN ('-', 'VACANTE')
	AND "NAME" NOT IN ('-', 'VACANTE')
ORDER BY 1,2,3
