WITH PLANNERS AS (
	SELECT DISTINCT
		'PLANEACION DE LA DEMANDA' AS "VP",
		"USER",
		"NAME"
	FROM WM_AD_HOC.TABLA_PLANEACION 
		UNPIVOT (
			("USER", "NAME") FOR PUESTO IN (
				(WM_PLANNER_ID, WM_PLANNER) AS 'PLANEADOR',
				(WM_GTE_PLANNER_ID, WM_GTE_PLANNER) AS 'GERENTE_PLANEADOR'
			)
		) AS A
),
RESURTIDORES_COMPRADORES AS (
	SELECT DISTINCT
		WM_VP_NOM AS "VP",
		"USER",
		"NAME"
	FROM WM_AD_HOC.TABLA_RESURTIDOR
		UNPIVOT (
			("USER", "NAME") FOR PUESTO IN (
				(WM_VICE_ID, WM_VICE) AS 'VP',
				(WM_DIR_COMPRAS_ID, WM_DIR_COMPRAS) AS 'DIRECTOR_COMPRAS',
				(WM_SUBDIR_COMPRAS_ID, WM_SUBDIR_COMPRAS) AS 'SUBDIRECTOR_COMPRAS',
				(WM_COMPRADOR_ID, WM_COMPRADOR) AS 'COMPRADOR',
				(WM_ASISTENTE_ID, WM_ASISTENTE) AS 'ASISTENTE',
				(WM_RESURTIDOR_ID, WM_RESURTIDOR) AS 'RESURTIDOR',
				(WM_SUB_DIR_RESURTIDO_ID, WM_SUB_DIR_RESURTIDO) AS 'SUBDIRECTOR_RESURTIDO',
				(WM_GTE_ID, WM_GTE) AS 'GERENTE_RESURTIDO',
				(WM_DIREC_ID, WM_DIREC) AS 'DIRECTOR_RESURTIDO'
			)
		) AS A
),
USUARIOS AS (
	SELECT *
	FROM PLANNERS
	
	UNION ALL
	
	SELECT *
	FROM RESURTIDORES_COMPRADORES

)

SELECT *
FROM USUARIOS
WHERE
	"USER" NOT IN ('-', 'VACANTE')
	AND "NAME" NOT IN ('-', 'VACANTE')
ORDER BY 1,2,3
;
