SELECT DISTINCT
	WM_VP_NOM AS "VP",
	/* ESTO OCUPA DEMASIADO ANCHO DE BANDA, ASI QUE LO OMITIMOS :(
	WM_DEPT AS DEPT_NBR,
	WM_NOM_DEPT AS DEPT_NAME,
	WM_CAT AS CATEGORY_NBR,
	WM_NOM_CAT AS CATEGORY_NAME,
	WM_FINELINE AS FINELINE,
	WM_VENDOR AS VENDOR,
	WM_DIV AS DIVISION,
	PUESTO,
	*/
	"USER",
	"NAME"
FROM WM_AD_HOC.TABLA_RESURTIDOR
	UNPIVOT (
		("USER", "NAME") FOR PUESTO IN (
			(WM_VICE_ID, WM_VICE) AS 'VP',
			(WM_DIR_COMPRAS_ID, WM_DIR_COMPRAS) AS 'DIRECTOR_COMPRAS',
			(WM_SUBDIR_COMPRAS_ID, WM_SUBDIR_COMPRAS) AS 'SUBDIRECTOR_COMPRAS',
			(WM_COMPRADOR_ID, WM_COMPRADOR) AS 'COMPRADOR',
			(WM_ASISTENTE_ID, WM_ASISTENTE) AS 'ASISTENTE',
			(WM_RESURTIDOR_ID, WM_RESURTIDOR) AS 'RESURTIDOR',
			(WM_SUB_DIR_RESURTIDO_ID, WM_SUB_DIR_RESURTIDO) AS 'SUBDIRECTOR_RESURTIDO',
			(WM_GTE_ID, WM_GTE) AS 'GERENTE_RESURTIDO',
			(WM_DIREC_ID, WM_DIREC) AS 'DIRECTOR_RESURTIDO'
		)
	) AS A
WHERE
	"USER" NOT IN ('-', 'VACANTE')
	AND "NAME" NOT IN ('-', 'VACANTE')
ORDER BY 1,2
;
